### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/docs#122]
```
/Users/danbjoseph/Documents/GitHub/OpenDroneMap/docs/source/arguments.rst:: WARNING: rST localisation for language "sw" not found.
```
```
/Users/danbjoseph/Documents/GitHub/OpenDroneMap/docs/source/argument/auto-boundary.rst::rST localisation for language "sw" not found.
```
A variation of the above error tends to show up for sw, te, and fil languages. 

Sphinx as a list of supported languages https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language
which does not include `fil` or `sw` but does include `te`

clean clone of the repo, running `make build` logs the first error (and due to nit-picky mode exits)
running `make allerr` logs all the errors but doesn't exit
running `make build` after `make allerr` successfully completes?

**Comment by pierotofy** [comment]
How about removing the `-W` flag from the `SPHINXBUILD` command for unsupported languages? The error seems just a warning anyway.

**Comment by danbjoseph** [comment]
resolved this. unfortunately without ever really figuring out the core issue and why certain languages seemed to catch. closing this and can revisit in the future if the problem returns or if inspired to research the issue again.
