### ISSUE TITLE
Update docs to reflect API / flag changes

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/docs#13]
We have a lot of small and some large changes to the API. With the [upcoming 0.5 release](https://github.com/OpenDroneMap/ODM/pull/921) we should catch up on API changes.

Additions:
```--mve-confidence```
```--smrf-scalar```
```--smrf-slope```
```--smrf-threshold```
```--smrf-window```

@pierotofy -- can you list the subtractions?

**Comment by pierotofy** [comment]
Removed: 
`--smvs-alpha`
`--smvs-output-scale`
`--smvs-enable-shading`
`--smvs-gamma-srgb`
`--start_with`
`--force-focal`
`--force-ccd`
`--orthophoto-target-srs`
`--zip-results`

I think these are all.

**Comment by smathermather** [comment]
I had intended to do this as a pull request, but, sigh:
https://github.com/OpenDroneMap/docs/commit/538b176c06b309b2a72f3b9ec6f5e7ed99ea0a10
https://github.com/OpenDroneMap/docs/commit/59f3b12ca060b4ef7bf87fa92a8d8b2828ab15b2

**Comment by smathermather** [comment]
Also remove --dem-terrain-type. See https://github.com/OpenDroneMap/docs/commit/8f9c79e5f1df7e76b7a297d194da19e8291b1f6a

**Comment by smathermather** [comment]
Aaand, PMF related parameters:
```
--dem-maxangle
--dem-maxsd <positive float>	
--dem-initial-distance
--dem-approximate
```
https://github.com/OpenDroneMap/docs/commit/af8cc7e7136e632fab4498b3d92cd73bd1dd694b
