### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by ruifortes** [OpenDroneMap/docs#141]
Guess there's an extra "&" in "$ ./webodm.sh start&" [here](https://docs.opendronemap.org/installation/#step-4-launch-webodm)

**Comment by Saijin-Naib** [comment]
Yikes!

Great catch! Thank you so much.

We're actually missing a space between "start" and the ampersand "&". What this does is fork the command to the background and let it run without needing the console open.

**Comment by ruifortes** [comment]
Thanks for the reminder. My Linux skills are a little rusty :-)

**Comment by Saijin-Naib** [comment]
That's all good, my proof-reading skills are too, apparently!
