### ISSUE TITLE
Regression in singularity documentation

### ISSUE THREAD

**Issue by Gouderg** [OpenDroneMap/docs#195]
I was working with singularity documentation and this [commit](https://github.com/OpenDroneMap/docs/commit/8b6eec1998a8a94f198a4c9f83418e14fa24cd30) remove some useful code example.

**Comment by smathermather** [comment]
That's a fair assessment. I wasn't sure how useful that was, and given it was removed in the pull request that otherwise looked fine, I went with it.

Would you be willing to open a pull request to add it back in?

**Comment by Gouderg** [comment]
Yes of course, here my [PR](https://github.com/OpenDroneMap/docs/pull/196).

**Comment by sbonaime** [comment]
I have an error with 75be20267418600965c5d933c33e51bb736293ad which is linked with singularity  
````
/gpfs/users/bonaime/git/docs/source/tutorials.rst:311: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 5 supplied.

.. code:: bash
   singularity pull --disable-cache  docker://opendronemap/odm:latest
/gpfs/users/bonaime/git/docs/source/tutorials.rst:316: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 5 supplied.

.. code:: bash
   singularity pull --disable-cache  docker://opendronemap/odm:gpu
````
@Gouderg @smathermather Can you start 'make livehtml' without error with 75be20267418600965c5d933c33e51bb736293ad ?

**Comment by sbonaime** [comment]
If I restart 'make livehtm', I don't have the error !
