### ISSUE TITLE
DTM + Web ODM

### ISSUE THREAD

**Issue by gyps-360** [OpenDroneMap/docs#231]
Hello,
I'm new using Web ODM.
I use Drone link for Fully automated missions and orthophoto acquisition.
I fly with a DJI Air 2 S.
I discovered the Digital Surface Model Tool in Web ODM but i would also be interested in Digital Terrain Model.
Is it possible to obtain DTM in Web ODM ?
How should I proceed to do so?

Thanks in adavance for your support

**Comment by smathermather** [comment]
Please post your query on the Community Forum: community.opendronemap.org. We reserve the issues for bugs and such, not support.

I look forward to seeing you in the forum!
