### ISSUE TITLE
Cannot launch Web ODM any more

### ISSUE THREAD

**Issue by gyps-360** [OpenDroneMap/docs#232]
I obtain the following message when I want to  launch Web ODM : exceeded max entries. If you have a fire wall make sure web ODM is allowed, the restart the application.

**Comment by gyps-360** [comment]
![image](https://github.com/user-attachments/assets/1b0ab58f-7e32-4741-ba13-01540ecc1f83)

**Comment by smathermather** [comment]
If this was installed via the paid for installer, please reach out to help@opendronemap.org. If it is installed via docker, please post your query on the Community Forum: community.opendronemap.org. We reserve the issues for bugs and such, not support.

I look forward to seeing you in email or the forum!
