### ISSUE TITLE
Where would I need to add a favicon

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/docs#4]
We should add an ODM favicon to this. Where would I put this?

**Comment by danbjoseph** [comment]
i think you should just be able to add `html_favicon="_static/favicon.ico"` as a line in `source/conf.py` 

http://www.sphinx-doc.org/en/master/config.html#confval-html_favicon

**Comment by danbjoseph** [comment]
happy to test if you want

**Comment by smathermather** [comment]
Yup. Hoping to have time Monday. Thanks!
