### ISSUE TITLE
build for different languages

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/docs#49]
need to figure out how to get the build process to create the html for all translated languages
i think this probably includes (at  least) some more stuff in the [Makefile#L21](https://github.com/OpenDroneMap/docs/blob/publish/Makefile#L21)

**Comment by smathermather** [comment]
@danbjoseph, @indiajohnson-cm will dive in for a try. If you have projects that have done this you can point to, that would be super nice. But at first blush, it looks pretty doable.
