### ISSUE TITLE
code snippet formatting problem

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/docs#61]
**something is wrong here...**

<img width="712" alt="Screen Shot 2020-08-07 at 6 21 48 PM" src="https://user-images.githubusercontent.com/4806884/89692909-f306ca00-d8da-11ea-9984-458d995d87cd.png">

 **and it's wrong + wrong some more in the Swahili...**
<img width="1063" alt="Screen Shot 2020-08-07 at 6 21 56 PM" src="https://user-images.githubusercontent.com/4806884/89692913-f4d08d80-d8da-11ea-999a-b78b2c0e1459.png">

**What should that first code snippet be? (on https://docs.opendronemap.org/tutorials.html)**

**Comment by smathermather** [comment]
The good news is we replaced that bit of advice with better code making the use of `exiftool` unnecessary, so it can be removed altogether. I'm on vacation for the week, but can take it out after the 15th if someone doesn't beat me to it. :D

**Comment by smathermather** [comment]
So, do I leave these open until they get updated in Swahili and Arabic? :)

**Comment by danbjoseph** [comment]
i think a deletion automatically propagates across the other languages?

**Comment by smathermather** [comment]
It looks like it: https://docs.opendronemap.org/sw/tutorials.html#using-docker
