### ISSUE TITLE
split/merge clarification

### ISSUE THREAD

**Issue by spifftek70** [OpenDroneMap/docs#7]
With regards to the use of GCPs and the split/merge function, at what point in the process does ODM apply the GCP list?  Within the split or the merge?  In other words, does each subarea split by this function need to contain at least 3 - 5 GCPs or is the entire area good with a total of 3 - 5 GCPs?

For example, a large area is split into four subareas by this function.  Does each subarea need 4 GCPs for a grand total of 16 GCPs or is the entire area good with a grand total of 4 GCPs?

**Comment by dakotabenjamin** [comment]
That's a really good question, one I have not tested yet. GCPs are used in the sparse point cloud generation portion of sfm, which for split-merge happens over the entire region of interest. In theory in your example you would only need 4 GCPs. If this is not the case, please let us know so we can clarify the docs

**Comment by smathermather** [comment]
@spifftek70 -- do you have time to test this? I'd love to know the answer too.

**Comment by pierotofy** [comment]
This is now clarified in https://docs.opendronemap.org/large.html at the end of the page.
