### ISSUE TITLE
argument descriptions not translated

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/docs#76]
Because the descriptive text is inside a code block, it's not transferred to Transifex for translation. See options A, B, C, D for fixes that have different impacts on the styling.

### How it looks now:

<img width="790" alt="Screen Shot 2020-11-06 at 2 50 48 PM" src="https://user-images.githubusercontent.com/4806884/98408721-a482dc00-203f-11eb-83f7-3ae05399c351.png">

### [A] One option would be to pull the descriptions out from the code blocks?

<img width="796" alt="Screen Shot 2020-11-06 at 2 51 00 PM" src="https://user-images.githubusercontent.com/4806884/98408772-b49abb80-203f-11eb-80ae-eb55cdd19c91.png">

### [B] Does a horizontal rule between each one help organize the page?

<img width="794" alt="Screen Shot 2020-11-06 at 2 53 49 PM" src="https://user-images.githubusercontent.com/4806884/98408909-f297df80-203f-11eb-8aab-46361cfe67a0.png">

### [C] Or an unordered list?

<img width="797" alt="Screen Shot 2020-11-06 at 3 05 09 PM" src="https://user-images.githubusercontent.com/4806884/98409866-9930b000-2041-11eb-83d4-291bc31cfacb.png">

###  [D] Or drop the code blocks entirely?

<img width="790" alt="Screen Shot 2020-11-06 at 3 08 30 PM" src="https://user-images.githubusercontent.com/4806884/98410069-f88ec000-2041-11eb-9f01-df5767174ce4.png">

**Comment by smathermather** [comment]
D reads the best, in my opinion.

**Comment by danbjoseph** [comment]
cool, will implement D.

**Comment by gastgit** [comment]
maybe it's me but on ubuntu/chrome version D looks like this

![image](https://user-images.githubusercontent.com/62561076/99272963-183b9a80-2831-11eb-9ded-7c3d62786122.png)

The list gets cut off. 

It looks good here: https://github.com/OpenDroneMap/docs/blob/publish/source/arguments.rst

But gets cut off here: https://docs.opendronemap.org/arguments.html

**Comment by israelbar** [comment]
I can confirm, in W10/Edge browser, but text is hidden not cut.
 
![2020-11-16_09-57-49](https://user-images.githubusercontent.com/55030037/99276843-b4927c80-27f2-11eb-9854-14a9b700173b.gif)

**Comment by danbjoseph** [comment]
when building locally it looks like the below. I will need to investigate why the Travis-CI build process is creating something different.
<img width="759" alt="Screen Shot 2020-11-16 at 11 05 09 AM" src="https://user-images.githubusercontent.com/4806884/99277293-a39a3900-27fb-11eb-81d3-e540e36d1d5a.png">

**Comment by gastgit** [comment]
> when building locally it looks like the below. I will need to investigate why the Travis-CI build process is creating something different.
> <img alt="Screen Shot 2020-11-16 at 11 05 09 AM" width="759" src="https://user-images.githubusercontent.com/4806884/99277293-a39a3900-27fb-11eb-81d3-e540e36d1d5a.png">

right that's how I thought it should look

**Comment by danbjoseph** [comment]
i was developing and testing using a newer version of Sphinx than noted in the requirements file. upgraded in 9233806706955abc11caf5fa0c2ca5341d802327 and it should now be displaying as expected on the website.

**Comment by gastgit** [comment]
Looks good on my side. Tnx!

**Comment by gastgit** [comment]
I also saw that the description on the `--feature-quality` is not correct. I tried to run it and got 
`run.py: error: argument --feature-quality: invalid choice: 'true' (choose from 'ultra', 'high', 'medium', 'low', 'lowest')` which actually fits the code here https://github.com/OpenDroneMap/ODM/blob/9a069f0d91cf7cbcdcb17491d1f7251fc12efd1e/opendm/config.py#L89
and here
https://github.com/OpenDroneMap/ODM/blob/9a069f0d91cf7cbcdcb17491d1f7251fc12efd1e/opendm/config.py#L151

The current description is very confusing in terms of what is needed in order to get it to work and what are the options
![image](https://user-images.githubusercontent.com/62561076/99508272-1686e980-298d-11eb-995b-b781519d9cf4.png)
