### ISSUE TITLE
hanging sentence in arguments?

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/docs#77]
description text seems incomplete/hanging (see screenshot)

<img width="737" alt="Screen Shot 2020-11-09 at 1 27 18 PM" src="https://user-images.githubusercontent.com/4806884/98581348-5b28cb80-228f-11eb-908e-cfe405754dde.png">

**Comment by smathermather** [comment]
I suspect this is the same as --samplespernode: http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version13.71/#USAGE

I'll have a patch shortly.
