### ISSUE TITLE
description for `--feature-quality` is not correct

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/docs#80]
I also saw that the description on the `--feature-quality` is not correct. I tried to run it and got 
`run.py: error: argument --feature-quality: invalid choice: 'true' (choose from 'ultra', 'high', 'medium', 'low', 'lowest')` which actually fits the code here https://github.com/OpenDroneMap/ODM/blob/9a069f0d91cf7cbcdcb17491d1f7251fc12efd1e/opendm/config.py#L89
and here
https://github.com/OpenDroneMap/ODM/blob/9a069f0d91cf7cbcdcb17491d1f7251fc12efd1e/opendm/config.py#L151

The current description is very confusing in terms of what is needed in order to get it to work and what are the options
![image](https://user-images.githubusercontent.com/62561076/99508272-1686e980-298d-11eb-995b-b781519d9cf4.png)

_Originally posted by @gastgit in https://github.com/OpenDroneMap/docs/issues/76#issuecomment-729536447_

**Comment by gastgit** [comment]
Great tnx !
