### ISSUE TITLE
Please allow the addition of new translation languages in transifex.

### ISSUE THREAD

**Issue by JOJOforshaun** [OpenDroneMap/docs#96]
I asked for a Chinese translator in the project at https://www.transifex.com/americanredcross/opendronemap_docs/. Please agree to join this language so that people can translate the document into Chinese.

**Comment by danbjoseph** [comment]
i accepted your request and added you as a translator.
please read the guidance about providing translations: https://github.com/OpenDroneMap/docs#translations
