### ISSUE TITLE
OpenDroneMap Outputs > Orthophoto - Incorrect Documentation

### ISSUE THREAD

**Issue by fishcharlie** [OpenDroneMap/docs#97]
The documentation at [this link](https://docs.opendronemap.org/outputs.html#orthophoto), is not accurate.

Off the bat I noticed the following discrepancies:

- A `.png` file does not exist in the output
- `odm_orthophoto.original.tif` exists in output but no summary exists in documentation
- `odm_orthophoto_render.tif` exists in output but no summary exists in documentation

Mostly I'm curious about the difference between `odm_orthophoto.original.tif` and `odm_orthphoto.tif`. But no documentation exists describing the difference between the two files.

**Comment by danbjoseph** [comment]
Thanks for flagging this @fishcharlie, I think this should be updated now (and live on the docs site).
https://docs.opendronemap.org/outputs/#orthophoto
Let us know if there is something else.
