### ISSUE TITLE
Travis build is shutting down

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/docs#99]
![image](https://user-images.githubusercontent.com/1951843/121200157-84b7ce80-c841-11eb-81a9-a422a339cdd1.png)

Looks like there's a week to move onto something different (GitHub actions)?

**Comment by danbjoseph** [comment]
i think they still offer free builds for open source projects that don't use much resources (like this one). it's just going to be all on one website instead of on 2. but i will look into this.

**Comment by danbjoseph** [comment]
for now, have changed the makefile to deploy from local. will investigate CI options in the future.

**Comment by pierotofy** [comment]
I recommend to check GitHub actions, they work pretty well and have a vibrant ecosystem.

**Comment by danbjoseph** [comment]
I think I misread the GitHub actions pricing when I first read it. I thought the 2,000 minutes free limit was on all repositories, but it looks like that's just private repos, and public repos are completely free?

**Comment by pierotofy** [comment]
Yep, free for public / open source.

**Comment by danbjoseph** [comment]
moved over to GitHub Actions by @pierotofy and wrapped up with #107
